POST http://localhost:8000/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "sssaksjnsdl",
    "password": "Ssss1234",
    "password2": "Ssss1234",
    "email": "sajnksgasjn@gmail.com"
}
###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "akjnsdl",
    "password": "Ssss1234"
}
###
POST http://localhost:8000/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "sssaksjnsdl",
    "password": "Ssss1234"
}
###
POST http://localhost:8000/reset-password/ HTTP/1.1
Content-Type: application/json

{
    "email": "h"
}
###
POST http://localhost:8000/reset-password-request/ HTTP/1.1
Content-Type: application/json

{
    "email": "m@gmail.com"
}
###
POST http://localhost:8000/reset-password/ HTTP/1.1
Content-Type: application/json

{
    "token":"1:1vQQuP:0uhARRg9CmP2ZmigPGcY80O_vI0LNERr79c134BScHU",
    "password":"Aaaa1234",
    "password2":"Aaaa1234"
}
###
POST http://localhost:8000/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "m",
    "password": "Aaaa1234"
}

###
GET http://localhost:8000/account/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0Njg4MjIzLCJpYXQiOjE3NjQ2ODc5MjMsImp0aSI6IjgyZTlhM2VhZDEwYjRlOTA4MjgxNmJlODkzNTg1MmE2IiwidXNlcl9pZCI6IjEifQ.Hvg8m7wh7D6ftsBNXPnDo0L_kV8ggArCYwUbE2ck_qY 
###
PUT http://localhost:8000/account/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0Njg5MTkyLCJpYXQiOjE3NjQ2ODg4OTIsImp0aSI6IjE3ODBhYTlmNTY4MzRhYjFiMWQ0N2YyZmU2MDUxMjJiIiwidXNlcl9pZCI6IjEifQ.V5g6W_LrqlhQ6X3wITJIJaUf83Qu0ah_ZnEr2Oiikv8
Content-Type: application/json

{
    "first_name":"ro"
}
